application: color-quest
version: 10
runtime: python
api_version: 1

handlers:
- url: /
  script: intro.py

- url: /gameplay
  script: colorquest.py

- url: /images
  static_dir: images

- url: /gameplay_start\.html
  script: initialize.py

- url: /endgame\.html
  script: end.py

- url: /dump
  script: dump.py

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
